#Configuración de Producción de Docker-Compose
version: '3.8'

services:
  db:
    #hereda base.db y solo añade el healthcheck
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    #hereda base.api
    volumes: []
    #expone el puerto en prod también
    ports:
      - "8080:8080"
