version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: juegos-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - juegos-data:/var/lib/mysql
    networks:
      - juegos-net

  api:
    build:
      context: ./docker       # <— apunta a la carpeta con tu Dockerfile
      dockerfile: Dockerfile
    container_name: juegosmesa_api
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - juegos-net

volumes:
  juegos-data:

networks:
  juegos-net:
